version: "3.7"

services:
  controller:
    build:
      context:  ./
      dockerfile: Dockerfile-controller
    networks:
    - node-tests
    environment:
    - ConfigurationOptions__DbPath=/etc/csi-controller/data
    volumes:
      - csi-controller-data:/etc/csi-controller/data

  node:
    build:
      context:  ./
      dockerfile: Dockerfile-node
    depends_on:
    - controller
    networks:
    - node-tests
    volumes:
    - csi-node-data:/tmp/csi-data-dir

  tests:
    build:
      context: ./
      dockerfile: Dockerfile-node-tests
    depends_on:
    - node
    volumes:
    - test-results:/test-results
    environment:
    - CONNECTION_STRING=http://node
    networks:
    - node-tests

volumes:
  csi-node-data:
  csi-controller-data:
  test-results:
    name: test-results

networks:
  node-tests:
