FROM mcr.microsoft.com/dotnet/sdk:7.0 AS base
WORKDIR /source
VOLUME /test-results

COPY ./tests/Csi.HostPath.Controller.Tests ./tests/Csi.HostPath.Controller.Tests/
COPY ./protos ./protos
RUN dotnet restore "tests/Csi.HostPath.Controller.Tests/Csi.HostPath.Controller.Tests.csproj"
CMD ["dotnet", "test", "tests/Csi.HostPath.Controller.Tests/Csi.HostPath.Controller.Tests.csproj", "--no-restore", "--results-directory", "/test-results", "--logger", "trx;LogFileName=testresults.trx"]