version: "3.7"

services:
  controller:
    build:
      context: ./../
      dockerfile: Dockerfile-controller
    restart: on-failure
    environment:
    - ConfigurationOptions__UnixSocket=/sockets/controller.sock
    - ConfigurationOptions__DbPath=/etc/csi-controller/data
    - ConfigurationOptions__ListeningPort=80
    ports:
    - 6000:80
    volumes:
       - /tmp/sockets/controller:/sockets
       - /tmp/data:/etc/csi-controller/data
    networks:
      - csi-plugin

  node:
    build:
      context: ./../
      dockerfile: Dockerfile-node
    restart: on-failure
    environment:
    - ConfigurationOptions__UnixSocket=/sockets/node.sock
    - ConfigurationOptions__CsiDataDir=/tmp/csi-data
    - ConfigurationOptions__ControllerEndpoint=http://controller  
    - ConfigurationOptions__NodeId=rusa-test
    - ConfigurationOptions__ListeningPort=80
    depends_on:
    - controller
    ports:
    - 6001:80
    volumes:
       - /tmp/sockets/node:/sockets
       - /tmp/csi-data-dir:/tmp/csi-data-dir
    networks:
      - csi-plugin

networks:
  csi-plugin:
    name: csi-plugin-network
