---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "csi-controller-service-name" . }}
  labels:
    {{- include "csi-controller-service-labels" . | nindent 4 }}
spec:
  selector:
    {{- include "csi-controller-selectors" . | nindent 4 }}
  ports:
  - port: 80
