---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ include "csi-name" . }}
  labels:
    {{- include "csi-node-labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "csi-node-selectors" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "csi-node-labels" . | nindent 8 }}
    spec:
      # not sure if we really need this
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      # not sure if we really need this
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "instance.hetzner.cloud/is-root-server"
                operator: NotIn
                values:
                - "true"
      containers:
      - name: csi-node-driver-registrar
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0
        args:
        - --kubelet-registration-path=/var/lib/kubelet/plugins/csi.hostpath/socket
        volumeMounts:
        - name: plugin-dir
          mountPath: /run/csi
        - name: registration-dir
          mountPath: /registration
      - name: csi-node-driver
        image: ruslansavchuk/rusa-hostpath-csi-node:{{ $.Chart.Version }}
        imagePullPolicy: Always
        env:
        - name: ConfigurationOptions__UnixSocket
          value: /run/csi/socket
        - name: ConfigurationOptions__CsiDataDir
          value: /var/lib/csi-data-dir
        - name: ConfigurationOptions__ListeningPort
          value: {{ .Values.node.listeningPort }}
        - name: ConfigurationOptions__NodeId
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: ConfigurationOptions__ControllerEndpoint
          value: http://{{ include "csi-controller-service-name" . }}
        volumeMounts:
        - name: kubelet-dir
          mountPath: /var/lib/kubelet
          mountPropagation: "Bidirectional"
        - name: plugin-dir
          mountPath: /run/csi
        - name: device-dir
          mountPath: /dev
        - name: csi-data-dir
          mountPath: /var/lib/csi-data-dir
        securityContext:
          privileged: true
      volumes:
      - name: kubelet-dir
        hostPath:
          path: /var/lib/kubelet
          type: Directory
      - name: plugin-dir
        hostPath:
          path: /var/lib/kubelet/plugins/csi.hostpath/
          type: DirectoryOrCreate
      - name: registration-dir
        hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: Directory
      # it is the place where csi node will store its data
      - name: csi-data-dir
        hostPath:
          path: {{ .Values.node.dataDir }}
          type: DirectoryOrCreate
      - name: device-dir
        hostPath:
          path: /dev
          type: Directory
