apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ include "csi-name" . }}
  labels:
    {{- include "csi-driver" . | nindent 4 }}
spec:
  # Supports persistent and ephemeral inline volumes.
  volumeLifecycleModes:
  - Persistent
  # - Ephemeral
  # To determine at runtime which mode a volume uses, pod info and its
  # "csi.storage.k8s.io/ephemeral" entry are needed.
  podInfoOnMount: true
  # No attacher needed.
  attachRequired: false
  storageCapacity: true
  # Kubernetes may use fsGroup to change permissions and ownership 
  # of the volume to match user requested fsGroup in the pod's SecurityPolicy
  fsGroupPolicy: File