apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "csi-name" . }}
  labels:
    {{- include "csi-storage-class-labels" . | nindent 4 }}
  annotations:
    {{- if .Values.setAsDefault }}
    storageclass.kubernetes.io/is-default-class: true
    {{- else }}
    storageclass.kubernetes.io/is-default-class: false
    {{- end }}
provisioner: {{ include "csi-name" . }}
volumeBindingMode: WaitForFirstConsumer
