---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "csi-name" . }}
  labels:
    {{- include "csi-controller-labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "csi-controller-labels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "csi-controller-labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "csi-name" . }}
      containers:
      - name: csi-attacher
        image: registry.k8s.io/sig-storage/csi-attacher:v4.1.0
        args:
        - --default-fstype=ext4
        volumeMounts:
        - name: socket-dir
          mountPath: /run/csi
      - name: csi-resizer
        image: registry.k8s.io/sig-storage/csi-resizer:v1.7.0
        volumeMounts:
        - name: socket-dir
          mountPath: /run/csi
      - name: csi-provisioner
        image: registry.k8s.io/sig-storage/csi-provisioner:v3.4.0
        args:
        - --feature-gates=Topology=true
        - --default-fstype=ext4
        volumeMounts:
        - name: socket-dir
          mountPath: /run/csi
      - name: host-path-csi
        image: ruslansavchuk/rusa-hostpath-csi-controller:0.0.1
        imagePullPolicy: Always
        env:
        - name: ConfigurationOptions__UnixSocket
          value: unix:///run/csi/socket
        volumeMounts:
        - name: socket-dir
          mountPath: /run/csi
      - name: liveness-probe
        imagePullPolicy: Always
        image: registry.k8s.io/sig-storage/livenessprobe:v2.9.0
        volumeMounts:
        - mountPath: /run/csi
          name: socket-dir
      volumes:
      - name: socket-dir
        emptyDir: {}
