FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Csi.HostPath.Controller/Csi.HostPath.Controller.Api/Csi.HostPath.Controller.Api.csproj", "Csi.HostPath.Controller/Csi.HostPath.Controller.Api/Csi.HostPath.Controller.Api.csproj"]
COPY ["Csi.HostPath.Controller/Csi.HostPath.Controller.Application/Csi.HostPath.Controller.Application.csproj", "Csi.HostPath.Controller/Csi.HostPath.Controller.Application/Csi.HostPath.Controller.Application.csproj"]
COPY ["Csi.HostPath.Controller/Csi.HostPath.Controller.Domain/Csi.HostPath.Controller.Domain.csproj", "Csi.HostPath.Controller/Csi.HostPath.Controller.Domain/Csi.HostPath.Controller.Domain.csproj"]
COPY ["Csi.HostPath.Controller/Csi.HostPath.Controller.Infrastructure/Csi.HostPath.Controller.Infrastructure.csproj", "Csi.HostPath.Controller/Csi.HostPath.Controller.Infrastructure/Csi.HostPath.Controller.Infrastructure.csproj"]
RUN dotnet restore "Csi.HostPath.Controller/Csi.HostPath.Controller.Api/Csi.HostPath.Controller.Api.csproj"
COPY Csi.HostPath.Controller Csi.HostPath.Controller
COPY Protos Protos

FROM build AS publish
RUN dotnet publish "Csi.HostPath.Controller/Csi.HostPath.Controller.Api/Csi.HostPath.Controller.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Csi.HostPath.Controller.Api.dll"]
