FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Csi.HostPath.Node/Csi.HostPath.Node.Api/Csi.HostPath.Node.Api.csproj", "Csi.HostPath.Node/Csi.HostPath.Node.Api/"]
RUN dotnet restore "Csi.HostPath.Node/Csi.HostPath.Node.Api/Csi.HostPath.Node.Api.csproj"
COPY Csi.HostPath.Node Csi.HostPath.Node
COPY Protos Protos

FROM build AS publish
ARG BUILD_VERSION=0.0.1
ENV CSI_DRIVER_VERSION=$BUILD_VERSION
RUN dotnet publish "Csi.HostPath.Node/Csi.HostPath.Node.Api/Csi.HostPath.Node.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Csi.HostPath.Node.Api.dll"]
