name: ci

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: commit
        name: Get commit info
        uses: prompt/actions-commit-hash@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Node images
        uses: docker/build-push-action@v5
        with:
          context: ./src/
          file: ./src/Dockerfile-node
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rusa-hostpath-csi-node:${{ steps.commit.outputs.short }}

      - name: Build and push Controller images
        uses: docker/build-push-action@v5
        with:
          context: ./src/
          file: ./src/Dockerfile-node
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rusa-hostpath-csi-controller:${{ steps.commit.outputs.short }}

      - name: Prepare build artifacts
        run: |
          sed -i 's/version: 0.0.1/version: ${{ steps.commit.outputs.short }}/g' ./deploy/rusa-csi-driver-host-path/Chart.yaml
          sed -i 's/appVersion: 0.0.1/appVersion: ${{ steps.commit.outputs.short }}/g' ./deploy/rusa-csi-driver-host-path/Chart.yaml

      - name: Publish build artifact
        uses: actions/upload-artifact@v3
        with:
          name: rusa-csi-driver-host-path
          path: ./deploy/rusa-csi-driver-host-path
