name: ci

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: Get commit info
        uses: prompt/actions-commit-hash@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Node images
        uses: docker/build-push-action@v5
        with:
          context: ./src/
          file: ./src/Dockerfile-node
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rusa-hostpath-csi-node:${{ steps.commit.outputs.short }}

      - name: Build and push Controller images
        uses: docker/build-push-action@v5
        with:
          context: ./src/
          file: ./src/Dockerfile-node
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rusa-hostpath-csi-controller:${{ steps.commit.outputs.short }}
